import { defineSchema, defineTable } from "convex/server";
import { v } from "convex/values";

export default defineSchema({
  // Teams table - represents golf carts/teams
  teams: defineTable({
    name: v.string(),
    color: v.string(), // Hex color for team identification
    // Note: score is computed from approved scores, not stored directly
  }).index("by_name", ["name"]),

  // Users table - players in the game
  users: defineTable({
    name: v.string(),
    handicap: v.number(),
    teamId: v.id("teams"),
    avatarUrl: v.optional(v.string()), // Generated by Nano Banana Pro
    avatarStorageId: v.optional(v.id("_storage")), // Convex file storage reference
    role: v.union(v.literal("captain"), v.literal("player")),
    hasSnake: v.boolean(), // The dreaded 3-putt snake flag
  })
    .index("by_team", ["teamId"])
    .index("by_has_snake", ["hasSnake"]),

  // Scores table - individual hole scores with approval workflow
  scores: defineTable({
    playerId: v.id("users"),
    teamId: v.id("teams"),
    hole: v.number(), // 1-18
    strokes: v.number(), // Gross strokes (actual shots taken)
    putts: v.number(),
    par: v.number(), // Par for the hole
    holeIndex: v.number(), // Difficulty index 1-18 (1 = hardest)
    netScore: v.number(), // Net score after handicap adjustment
    shotsReceived: v.number(), // Handicap strokes received on this hole
    status: v.union(
      v.literal("pending"),
      v.literal("approved"),
      v.literal("rejected")
    ),
    inputBy: v.id("users"), // Who entered this score
    approvedBy: v.optional(v.id("users")), // Captain who approved/rejected
    approvedAt: v.optional(v.number()), // Timestamp of approval
  })
    .index("by_player", ["playerId"])
    .index("by_team", ["teamId"])
    .index("by_status", ["status"])
    .index("by_player_hole", ["playerId", "hole"])
    .index("by_team_status", ["teamId", "status"]),

  // Feed items - the social activity stream
  feed_items: defineTable({
    type: v.union(
      v.literal("birdie"),
      v.literal("eagle"),
      v.literal("snake"),
      v.literal("sabotage"),
      v.literal("info"),
      v.literal("powerup"),
      v.literal("score")
    ),
    message: v.string(),
    mediaUrl: v.optional(v.string()), // Optional image/gif
    mediaStorageId: v.optional(v.id("_storage")),
    timestamp: v.number(),
    // Optional references for rich rendering
    playerId: v.optional(v.id("users")),
    teamId: v.optional(v.id("teams")),
    targetTeamId: v.optional(v.id("teams")), // For sabotage events
  }).index("by_timestamp", ["timestamp"]),

  // Power-ups - special abilities for chaos
  powerups: defineTable({
    userId: v.id("users"),
    type: v.union(
      v.literal("mulligan"), // Re-do a shot, remove worst score
      v.literal("grenade"), // Add strokes to another team
      v.literal("club_theft") // Steal a club from another team
    ),
    status: v.union(v.literal("available"), v.literal("played")),
    usedAt: v.optional(v.number()), // When the powerup was used
    targetTeamId: v.optional(v.id("teams")), // Who was targeted
  })
    .index("by_user", ["userId"])
    .index("by_user_status", ["userId", "status"])
    .index("by_type", ["type"]),

  // Course configuration (optional, for par values)
  holes: defineTable({
    number: v.number(), // 1-18
    par: v.number(), // 3, 4, or 5
    index: v.number(), // Stroke index / difficulty (1-18, 1 = hardest)
    name: v.optional(v.string()), // e.g., "Devil's Elbow"
  }).index("by_number", ["number"]),
});
